apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-omsorgspenger-midlertidig-alene-mottatt
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730  # -1 means unlimited
  acl:
    - team: dusseldorf
      application: omsorgspenger-midlertidig-alene-api
      access: write
    - team: dusseldorf
      application: omsorgspenger-midlertidig-alene-prosessering
      access: read

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-omsorgspenger-midlertidig-alene-preprossesert
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730  # -1 means unlimited
  acl:
    - team: dusseldorf
      application: omsorgspenger-midlertidig-alene-prosessering
      access: readwrite

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-omsorgspenger-midlertidig-alene-cleanup
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730  # -1 means unlimited
  acl:
    - team: dusseldorf
      application: omsorgspenger-midlertidig-alene-prosessering
      access: readwrite
